service: demo-sls

provider:
  name: aws
  runtime: nodejs6.10

#  stage: dev
  region: eu-central-1


functions:
  # Function-definisjon for Lambdaen vår
  demo-sls:
    handler: handler.demo_sls
    events:
      - http: ANY todos


