service: demo-sls

provider:
  name: aws
  runtime: nodejs6.10

  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:DescribeTable
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"

functions:
  demo-sls:
    handler: handler.demo_sls
    events:
      - http: 
          path: todos
          method: GET
      - http:
          path: todos
          method: POST
          authorizer: authorizerFunc
      - http:
          path: todos
          method: DELETE
          authorizer: authorizerFunc
  authorizerFunc:
    handler: authorizer.authorizerFunc

resources:
  Resources:
    Tabell:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: demo-sls
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: text
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
          - AttributeName: text
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1